export type Status = 'Open' | 'In progress' | 'Awaiting verification' | 'Resolved' | 'Compliant' | 'Needs review';
export interface Detection { classId:number; label:string; confidence:number; box:[number,number,number,number]; }
export interface Analysis { model:string; modelSha256:string; threshold:number; width:number; height:number; detections:Detection[]; persons:number; missingHelmets:number; missingVests:number; warnings:string[]; elapsedMs:number; analyzedAt:string; runtime:string; }

export interface Site { id: string; name: string; location: string; zones: string[]; }
export interface Inspection { source?:'manual'|'yolo'; analysis?:Analysis; verificationAnalysis?:Analysis; id: string; site: string; zone: string; created: string; helmets: number; vests: number; multiple: boolean; repeat: boolean; critical: boolean; score: number; status: Status; owner: string; due: string; notes: string; image: string; followup: string; history: {time:string; text:string}[]; demo: boolean; }
export interface Store { version: number; sites: Site[]; inspections: Inspection[]; }
export const risk = (n:number) => n >= 80 ? 'Critical' : n >= 60 ? 'High' : n >= 30 ? 'Medium' : 'Low';
export const riskClass = (n:number) => n >= 60 ? 'badge-error' : n >= 30 ? 'badge-warning' : 'badge-success';
export const isActive = (i:Inspection) => i.status !== 'Resolved' && i.status !== 'Compliant';
export const scoreFor = (h:number,v:number,m:boolean,r:boolean,c:boolean) => Math.min(100,h*25+v*15+(m?10:0)+(r?10:0)+(c?25:0));
export const dateLabel = (s:string) => new Date(s).toLocaleDateString('en-IN',{day:'numeric',month:'short'});
export const seed = ():Store => {
 const sites:Site[]=[{id:'s1',name:'Skyline Residences',location:'Vellore · Residential',zones:['Tower A','Tower B','Material yard']},{id:'s2',name:'Metro Connect',location:'Chennai · Infrastructure',zones:['North corridor','Station 04','Equipment bay']},{id:'s3',name:'TechPark East',location:'Bengaluru · Commercial',zones:['Block C','Loading dock','Main entrance']}];
 const rows = [ ['s1','Tower A',2,1,true,true,false,'Open','Arun Kumar'],['s2','North corridor',1,1,true,true,false,'In progress','Priya Sharma'],['s3','Block C',0,2,true,false,false,'Awaiting verification','Karthik S'],['s1','Material yard',1,0,false,false,false,'Open','Arun Kumar'],['s2','Station 04',0,1,false,false,false,'Resolved','Priya Sharma'],['s3','Main entrance',0,0,false,false,false,'Compliant','Karthik S'],['s1','Tower B',1,1,false,false,false,'Resolved','Arun Kumar'],['s2','Equipment bay',0,0,false,false,false,'Compliant','Priya Sharma'] ];
 return {version:1,sites,inspections:rows.map((a,k)=>{ const created=new Date(Date.now()-k*86400000).toISOString();return {id:`INS-${1048-k}`,site:a[0] as string,zone:a[1] as string,created,helmets:a[2] as number,vests:a[3] as number,multiple:a[4] as boolean,repeat:a[5] as boolean,critical:a[6] as boolean,score:scoreFor(a[2] as number,a[3] as number,a[4] as boolean,a[5] as boolean,a[6] as boolean),status:a[7] as Status,owner:a[8] as string,due:new Date(Date.now()+(k-1)*86400000).toISOString().slice(0,10),notes:'Illustrative record for the project demonstration. Not an AI detection or real site observation.',image:'',followup:'',history:[{time:created,text:'Sample inspection created for demonstration.'}],demo:true};})};
};
export async function readImage(file:File):Promise<string> { if(!['image/jpeg','image/png','image/webp'].includes(file.type)) throw Error('Choose a JPG, PNG or WebP image.'); if(file.size>8*1024*1024) throw Error('Please choose an image smaller than 8 MB.'); const src=await new Promise<string>((res,rej)=>{const f=new FileReader();f.onload=()=>res(String(f.result));f.onerror=()=>rej(Error('Image could not be read.'));f.readAsDataURL(file);}); const img=new Image();img.src=src;await img.decode(); const ratio=Math.min(1,1400/Math.max(img.width,img.height));const c=document.createElement('canvas');c.width=Math.round(img.width*ratio);c.height=Math.round(img.height*ratio);c.getContext('2d')!.drawImage(img,0,0,c.width,c.height);return c.toDataURL('image/jpeg',.8); }
export function downloadReport(items:Inspection[],sites:Site[]) { const rows=[['ID','Site','Zone','Date','Missing helmets','Missing vests','Risk score','Risk level','Status','Supervisor','Due','Source'],...items.map(i=>[i.id,sites.find(s=>s.id===i.site)?.name||i.site,i.zone,i.created,i.helmets,i.vests,i.score,risk(i.score),i.status,i.owner,i.due,i.demo?'Sample data':i.source==='yolo'?'YOLO26n':'Manual review'])]; const csv=rows.map(r=>r.map(v=>'"'+String(v).replace(/^[=+@\-]/,"'$&").replace(/"/g,'""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=url;a.download='construct-gaurd-inspections.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000); }
